Repository halo-sigs/plugin-links, pull requests merged in 2023-07, with the labels that each got.

#31 docs: update usage documentation of readme file
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#33 chore: optimize the project infrastructure
  .github/workflows/build.yml
  .gitignore
  build.gradle
  console/pnpm-lock.yaml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lib/halo-2.0.0-SNAPSHOT-plain.jar
  settings.gradle
  src/main/java/run/halo/links/LinkRouter.java
  src/main/resources/console/main.js
  src/main/resources/console/style.css
Labels: lgtm, kind/improvement, release-note, approved

#36 feat: add annotations form adaption support
  README.md
  console/src/components/GroupEditingModal.vue
  console/src/components/LinkEditingModal.vue
Labels: kind/feature, lgtm, release-note, approved
