Repository halo-sigs/plugin-links, pull requests merged in 2023-02, with the labels that each got.

#7 refactor: add route item to sidebar menu
  console/package.json
  console/pnpm-lock.yaml
  console/src/index.ts
  console/tsconfig.app.json
  console/vite.config.ts
  src/main/resources/console/main.js
Labels: lgtm, kind/improvement, release-note, approved

#8 chore: release 1.1.0
  gradle.properties
  src/main/resources/plugin.yaml
Labels: lgtm, release-note-none, approved

#11 fix: the default group is reset after restarting
  src/main/resources/extensions/groups.yaml
Labels: kind/bug, lgtm, release-note, approved

#14 feat: add pagination supports
  console/src/types/index.ts
  console/src/views/LinkList.vue
  src/main/resources/console/main.js
Labels: kind/feature, lgtm, release-note, approved

#15 fix: link management permission was assigned but still did not have permission
  src/main/resources/extensions/roleTemplate.yaml
Labels: lgtm, kind/improvement, release-note, approved
