Repository halo-sigs/plugin-links, pull requests merged in 2023-08, with the labels that each got.

#37 fix: moving the currently selected link will move all links
  console/src/views/LinkList.vue
Labels: lgtm, release-note, approved

#38 chore: add halo app store release step
  .github/workflows/build.yml
Labels: lgtm, kind/improvement, release-note-none, approved

#40 fix: can not submit in group form
  console/src/components/GroupEditingModal.vue
  console/src/components/LinkEditingModal.vue
Labels: kind/bug, lgtm, release-note, approved

#43 chore: upgrade the dependency to implement the ExtensionVoOperator interface for the VO classes
  build.gradle
  src/main/java/run/halo/links/vo/LinkGroupVo.java
  src/main/java/run/halo/links/vo/LinkVo.java
Labels: lgtm, release-note-none, approved

#41 feat: make logo form item type to attachment
  console/src/components/LinkEditingModal.vue
Labels: lgtm, kind/improvement, release-note, approved

#44 chore: update halo requires
  src/main/resources/plugin.yaml
Labels: lgtm, release-note-none, approved
