Repository halo-sigs/plugin-links, pull requests merged in 2024-01, with the labels that each got.

#52 feat: add page icon
  console/src/views/LinkList.vue
Labels: kind/feature, lgtm, release-note, approved

#51 fix: unable to refetch after deleting a link
  console/src/views/LinkList.vue
Labels: kind/bug, lgtm, release-note, approved

#54 fix：批量导入bug、关键字搜索无效
  console/src/views/LinkList.vue
Labels: lgtm, approved, do-not-merge/release-note-label-needed
