Repository halo-sigs/plugin-links, pull requests merged in 2024-06, with the labels that each got.

#66 feat: adapt to the comment plugin
  README.md
  build.gradle
  console/package.json
  console/pnpm-lock.yaml
  console/src/index.ts
  src/main/java/run/halo/links/LinkCommentSubject.java
  src/main/java/run/halo/links/LinkRouter.java
Labels: kind/feature, lgtm, release-note, approved

#67 feat: add page title configuration item
  README.md
  src/main/java/run/halo/links/LinkRouter.java
  src/main/resources/extensions/settings.yaml
  src/main/resources/plugin.yaml
Labels: lgtm, approved

#68 chore: rename 'Friend Links' to 'Links'
  console/src/index.ts
  src/main/java/run/halo/links/LinkCommentSubject.java
Labels: lgtm, kind/improvement, release-note-none, approved

#70 chore: update logo
  src/main/resources/logo.png
  src/main/resources/logo.svg
  src/main/resources/plugin.yaml
Labels: lgtm, kind/improvement, release-note-none, approved

#69 chore: update plugin.yaml
  src/main/resources/plugin.yaml
Labels: lgtm, approved

#74 fix: display issue when no groups are present
  console/src/views/LinkList.vue
Labels: kind/bug, lgtm, release-note, approved

#72 feat: one click fetch for basic website information
  .editorconfig
  console/src/components/LinkEditingModal.vue
  console/src/types/index.ts
  src/main/java/run/halo/links/LinkDetailDTO.java
  src/main/java/run/halo/links/LinkRequest.java
  src/main/java/run/halo/links/LinkRouter.java
Labels: kind/feature, lgtm, release-note, approved
